#!/bin/bash
echo "Configuration des variables d'environnement Vercel..."
echo "Copiez et exécutez ces commandes:"
echo ""
echo "vercel env add NEXTAUTH_SECRET production"
echo "# Entrez: qAOQq0/2GxTybJqV/GOKC34zM/tguUenONRdVY88nLw="
echo ""
echo "vercel env add AUTH_SECRET production"
echo "# Entrez: qAOQq0/2GxTybJqV/GOKC34zM/tguUenONRdVY88nLw="
echo ""
echo "vercel env add NEXT_PUBLIC_API_URL production"
echo "# Entrez: https://intowork-dashboard-production.up.railway.app/api"
echo ""
echo "Note: NEXTAUTH_URL est auto-détecté par Vercel"
