"""add nextauth models and update user

Revision ID: 411cd9a350e0
Revises: f6a0b4c3d2e1
Create Date: 2025-12-23 10:42:14.559343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411cd9a350e0'
down_revision: Union[str, None] = 'f6a0b4c3d2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tokens_id'), 'verification_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_verification_tokens_token'), 'verification_tokens', ['token'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_account_id', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('session_state', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_session_token'), 'sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.alter_column('candidate_cvs', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('idx_candidate_cvs_candidate_id'), table_name='candidate_cvs')
    op.drop_index(op.f('idx_candidate_cvs_is_active'), table_name='candidate_cvs')
    op.create_index(op.f('ix_candidate_cvs_id'), 'candidate_cvs', ['id'], unique=False)
    op.drop_constraint(op.f('candidate_cvs_candidate_id_fkey'), 'candidate_cvs', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_cvs', 'candidates', ['candidate_id'], ['id'])
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('image', sa.String(), nullable=True))
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'clerk_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'image')
    op.drop_column('users', 'name')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_constraint(None, 'candidate_cvs', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_cvs_candidate_id_fkey'), 'candidate_cvs', 'candidates', ['candidate_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_candidate_cvs_id'), table_name='candidate_cvs')
    op.create_index(op.f('idx_candidate_cvs_is_active'), 'candidate_cvs', ['is_active'], unique=False)
    op.create_index(op.f('idx_candidate_cvs_candidate_id'), 'candidate_cvs', ['candidate_id'], unique=False)
    op.alter_column('candidate_cvs', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_session_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_verification_tokens_token'), table_name='verification_tokens')
    op.drop_index(op.f('ix_verification_tokens_id'), table_name='verification_tokens')
    op.drop_table('verification_tokens')
    # ### end Alembic commands ###
