"""add cv fields to candidates table

Revision ID: b58fbc6d62f4
Revises: 2aa492e7cc3e
Create Date: 2025-12-16 16:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b58fbc6d62f4'
down_revision: Union[str, None] = '2aa492e7cc3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('cv_filename', sa.String(), nullable=True))
    op.add_column('candidates', sa.Column('cv_uploaded_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'cv_uploaded_at')
    op.drop_column('candidates', 'cv_filename')
    # ### end Alembic commands ###
